### ISSUE TITLE
build steps

### ISSUE THREAD

**Issue by gambhiro** [buddhiko1/pali-web#1]
Dear @buddhiko1 , the github recommendations led me to your project.

It gives me the impression that it is a web app for learning Pali, so I was curious to try.

What are the steps to setup and build it locally?

I got as far as `pnpm install` and `ng build`, but the typescript compiler gives me errors. Perhaps I'm using it with the wrong node version.

**Comment by Nirodhiko** [comment]
@gambhiro 
Hello~

This personal project is still under development and is a semi-finished product. I didn't want to show the semi-finished product to others, so I didn't write the build steps. 

Are you interested in participating in this project?

**Comment by gambhiro** [comment]
A screenshot or a description of what it might be in the future would be helpful.

What are your ideas for the project? Language tutorial pages, interactive learning, or similar?

**Comment by Nirodhiko** [comment]
@gambhiro 

This is the web : https://www.buddhiko.com

The biggest difficulty I encountered in learning Pali was the lack of high-quality learning materials, rather than the grammar of Pali itself. So I wanted to create a website that collects excellent learning resources. You can browse the homepage to understand what I want to achieve. This is a personal website, and I don't care about the length of time it takes, only the quality. This website can display content well on mobile/tablet/computer and provide 2 or more themes through configuration (only two have been done now). The completed modules are the user module/dictionary module/book module, and now I am working on the blog module.

I'm not sure if you're interested. The front-end technology stack is Angular and Tailwindcss, and the back-end uses Directus (CMS).

The pali page of 'Digital Pāli Reader' and 'SuttalCenter' is ugly.
I want to remake a module similar to 'Digital Pāli Reader',  but provide a better reading experience, such as more themes, better fonts, etc.

Unfortunately, I have to go find a job now, so I don't have much time. If this project is useful to you, you can clone it.

**Comment by gambhiro** [comment]
Thanks for pointing out the link, the website looks nice! I see you are setting up the basic framework atm, but it's definitely a good start.
